<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.7.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php

    $summaryForCustomer = $this->getSummaryForCustomer();
    $textForPoints = Mage::helper('points/config')->getPointUnitName();
  
 
    $paid_checkout = false;
    $ctr = 0;
    foreach ($this->getItems() as $item) {
        $productId = $item->getProductId();
	if($productId!='168'):
        $_product = Mage::getModel('catalog/product')->load($productId);
        $free_delivery_bool = $_product->getResource()->getAttribute('free_delivery')->getFrontend()->getValue($_product);
        if($free_delivery_bool != 'Yes') $paid_checkout = TRUE;
        else $ctr++;
	endif;
    }
    $points_todeduct  =  $ctr;
?>
<div class="sp-methods" style="margin: 0px 31%; width: 450px; margin-top: 90px;"> <?php if(!$paid_checkout):?> <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" />Please wait for a moment while we finalize your order...<?php endif;?><?php if($paid_checkout):?><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" />Please wait for a moment while we redirect you to paypal...<?php endif; ?></div>
<div class="sp-methods" id="checkout-payment-method-load" style="visibility:hidden;">
<?php if ($this->pointsSectionAvailable()): ?>
    <div> 
        <input type="checkbox" name="payment[use_points]" id="use_points" checked="checked" />
        <label for="use_points"><?php echo $this->__('Use my %s', $textForPoints) ?></label>
    </div>
    <div>
        <input type="text" name="payment[points_amount]" value ="<?php echo $points_todeduct; ?>" id="points_amount" onchange="pointsAmountChanged()" style="color: #000;
border: 1px solid;"/>
        <label for="points_amount"><?php echo Mage::helper('points')->__('of %s %s (%s) available', $summaryForCustomer->getPoints(), $textForPoints, $this->getMoneyForPoints()) ?></label>
    </div>
<?php endif; ?>
<?php $oneMethod = false;?>
<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
    <div><?php echo $_code;?>
        <?php if (sizeof($this->getMethods()) > 1): ?>
            <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')" <?php if ('paypal_express' == $_code && $paid_checkout): ?> checked="checked"<?php endif; ?> <?php if ('cashondelivery' == $_code && !$paid_checkout): ?> checked="checked"<?php endif; ?> class="radio" />
        <?php else: ?>
            <?php $oneMethod = $_method->getCode();?>
            <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
        <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
    </div>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
        <div>
            <?php echo $html; ?>
        </div>
    <?php endif; ?>
<?php endforeach; ?>
</div>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getChildChildHtml('scripts'); ?>
    payment.init();
    //payment.save();
   // $('#paynow').click();
    <?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
    
    <?php endif; ?>
    //]]>
</script>
<?php if ($this->pointsSectionAvailable()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var customerPoints = <?php echo $summaryForCustomer->getPoints() ?>;
        var neededPoints = <?php echo $this->getNeededPoints() ?>;
        var limitedPoints = <?php echo $this->getLimitedPoints() ?>;
        payment.save();
        $('use_points').disabled = $('points_amount').disabled = false;
        //$('points_amount').value = Math.abs(Math.min(customerPoints, neededPoints, limitedPoints)).toFixed(0);

        var pointsAmountChanged = function () {
            var points_amount = $('points_amount').value;
            if (isNaN(points_amount)) points_amount = 0;
            points_amount = Math.min(Math.abs(points_amount), customerPoints, neededPoints, limitedPoints);
            $('points_amount').value = Math.abs(points_amount).toFixed(0);
        };

        Event.observe(window, 'load', function()
        {   
            
              
            if (payment) {
                payment.copySave = payment.save;
                payment.anyPaymentMethodChecked = function () {
                    var methods = document.getElementsByName('payment[method]');
                    for (var i = 0; i < methods.length; i++) {
                        if (methods[i].checked) {
                            return true;
                        }
                    }
                    return false;
                };

                payment.save = function() {
                    
                     var quoteBaseGrandTotalInPoints = <?php echo $this->getBaseGrandTotalInPoints() ?>;
                     
                    if (quoteBaseGrandTotalInPoints > $('points_amount').value
                        && !payment.anyPaymentMethodChecked())      {
                        alert(Translator.translate('Please specify payment method.'));
                        return false;
                    } else  {
                        return payment.copySave();
                    }
                }
            }
        });
        //]]>
    </script>
<?php endif; ?>
