<ol>
<?php 
    $items = $this->getItems(); 
    list($from, $to) = explode(',', $items[0]->getValueString());
   
    if ($from < 0.01)
        $from = $this->__('From');
    if ($to < 0.01)
        $to = $this->__('To');
?>
<li>
<input class="input-text" type="text" maxlength="12" size="3" id="mmd-multinav-price-from" value="<?php echo $from?>"
onclick="if(this.value==this.name) this.value='';"  name="<?php echo $this->__('From')?>"/>
<span class="mmd-multinav-separator">-</span>
<input class="input-text" type="text" maxlength="12" size="3" id="mmd-multinav-price-to" value="<?php echo $to?>"
onclick="if(this.value==this.name) this.value='';" name="<?php echo $this->__('To')?>"/>
<input type="button" class="form-button" value="<?php echo $this->__('Go')?>" id="mmd-multinav-price-go"/>
</li>
</ol>