<!-- <link href="<?=$this->getSkinUrl('css/sa/membership.css');?>" rel="stylesheet" type="text/css" />
<div id="popup"><img src="<?=$this->getSkinUrl('images/ajax-loader.gif');?>"></div> -->
<!-- start Mixpanel -->
<script type="text/javascript">
	(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
	for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2.2.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
	mixpanel.init("c4d7924bdf21e04826846df38af78a12");
</script><!-- end Mixpanel -->
<script type="text/javascript" src="<?=$this->getJsUrl('jquery/jquery-1.9.0.min.js'); ?>"></script>
<script>
	// jQuery(document).ready(function($){
		// $("#popup").show();
	// });
	mixpanel.track("Activated");
	setTimeout(function(){ window.location.href = "/profile/index/"; }, 100);
</script>