<div class="container">
  <section class="content content-special">
    <aside class="sidebar sidebar2">
      <h2>sample store</h2>
      <ul>
        <li><a href="/site/about">about us</a></li>
        <li><a style="color:#5ed0fc !important;" href="/site/contact"><strong>contact us</strong></a></li>
        <li><a href="/site/faq">FAQ</a></li>
        <li><a href="https://www.samplestore.com/legal/terms_of_use.pdf" target="_blank">terms of use</a></li>
        <li><a href="https://www.samplestore.com/legal/tnc_for_members.pdf" target="_blank">terms &amp; conditions</a></li>
        <li><a href="https://www.samplestore.com/legal/privacy_policy.pdf" target="_blank">privacy policy</a></li>
        <li><a href="https://www.samplestore.com/legal/tnc_for_advertisers.pdf" target="_blank">advertiser's term</a></li>
      </ul>
    </aside>
    <!--sidebar ends-->
    <div class="right-content">
      <div class="title title2"><span>contact us</span></div>
      <div class="clearfix"></div>
      <div class="contact-block">
		<?=$this->getLayout()->createBlock('cms/block')->setBlockId('contact_us')->toHtml();?>	
      </div>
    </div>
    <!--right-content ends--> 
  </section>
</div>