<div class="title title2">
<span><?php echo $this->__('Coupon Status') ?></span>
</div>
<div class="table-wrap">
	<table class="notify">
		<thead>
			<tr>
				<th scope="col">Redeemed On</th>
				<th scope="col">Coupon Code</th>
				<th scope="col">Gift</th>
				<th scope="col">Qty</th>
				<th scope="col">Type</th>
				<th scope="col">Status</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>15 April 2014</td>
				<td>00000000</td>
				<td>Gift Name</td>
				<td>1</td>
				<td>None</td>
				<td>Pending</td>
			</tr>
		</tbody>
	</table>
</div>